version: "3.5"
 
services:
  broker:
    image: johnnypark/kafka-zookeeper:2.6.0
    container_name: service-broker
    restart: always
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
    - ADVERTISED_HOST=127.0.0.1
    - NUM_PARTITIONS=3
    networks:
    - aforo255
  tracer:
    image: openzipkin/zipkin:2
    container_name: service-tracer
    restart: always
    ports:
      - "9411:9411"
    networks:
    - aforo255 
 
networks:
  aforo255:
    name: micro-java-1